((((type . "package")
   (name . "axi_test")
   (beg-point)
   (end-point))
  . 954)
 (((type . "class")
   (name . "axi_lite_driver")
   (beg-point)
   (end-point))
  . 1074)
 (((type . "class")
   (name . "axi_lite_driver")
   (beg-point)
   (end-point))
  . 1245)
 (((type . "function")
   (name . "new")
   (beg-point)
   (end-point))
  . 1386)
 (((type . "function")
   (name . "new")
   (beg-point)
   (end-point))
  . 1433)
 (((type . "class")
   (name . "axi_scoreboard")
   (beg-point)
   (end-point))
  . 77731)
 (((type . "package")
   (name . "axi_test")
   (beg-point)
   (end-point))
  . 77760)
 (nil . 77772)
 (((type . "module")
   (name . "axi_chan_logger")
   (beg-point)
   (end-point))
  . 78713)
 (((type . "module")
   (name . "axi_chan_logger")
   (beg-point)
   (end-point))
  . 79365)
 (((type . "always")
   (name . "proc_channel_sample")
   (beg-point)
   (end-point))
  . 79753)
 (((type . "initial")
   (name . "proc_log")
   (beg-point)
   (end-point))
  . 82960)
 (((type . "module")
   (name . "axi_chan_logger")
   (beg-point)
   (end-point))
  . 86883)
 (nil . 86893))
