((((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 839)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 840)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 988)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 1288)
 (((type . "module_instantiation")
   (name . "cpu")
   (beg-point . 2335)
   (end-point . 3000))
  . 2699)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 4873)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 4874)
 (((type . "module_declaration")
   (name . "ucontroller")
   (beg-point . 834)
   (end-point . 4887))
  . 4888))
