((nil . 1790)
 (nil . 1840)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 1841)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 2747)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 7601)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 7602)
 (((type . "function")
   (name . "set_print_config_matches")
   (beg-point)
   (end-point))
  . 29886)
 (((type . "function")
   (name . "raised")
   (beg-point)
   (end-point))
  . 30879)
 (((type . "function")
   (name . "dropped")
   (beg-point)
   (end-point))
  . 31499)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 32030)
 (((type . "class")
   (name . "uvm_component")
   (beg-point)
   (end-point))
  . 58460)
 (nil . 58668)
 (((type . "function")
   (name . "new")
   (beg-point)
   (end-point))
  . 59430)
 (((type . "function")
   (name . "get_first_child")
   (beg-point)
   (end-point))
  . 63161)
 (((type . "task")
   (name . "run_phase")
   (beg-point)
   (end-point))
  . 76134)
 (((type . "task")
   (name . "pre_reset_phase")
   (beg-point)
   (end-point))
  . 76584)
 (((type . "task")
   (name . "pre_reset_phase")
   (beg-point)
   (end-point))
  . 76623)
 (nil . 76638)
 (nil . 100707)
 (((type . "function")
   (name . "m_do_pre_abort")
   (beg-point)
   (end-point))
  . 100752)
 (nil . 100839))
