(("*Instances*"
  ("spill_register" . 3689)
  ("spill_register" . 4161)
  ("spill_register" . 4622)
  ("spill_register" . 5077)
  ("spill_register" . 5549)
  ("spill_register" . 9163)
  ("spill_register" . 9668)
  ("axi_demux_id_counters" . 13911)
  ("counter" . 15375)
  ("spill_register" . 16156)
  ("spill_register" . 16714)
  ("rr_arb_tree" . 17182)
  ("spill_register" . 17879)
  ("spill_register" . 18324)
  ("axi_demux_id_counters" . 21519)
  ("spill_register" . 23003)
  ("rr_arb_tree" . 23471)
  ("delta_counter" . 31764)
  ("axi_demux" . 35418))
 ("*Initial blocks*"
  ("no_mst_ports: assume (NoMstPorts > 0) else" . #<marker at 25927 in axi_demux.sv>))
 ("*Always blocks*"
  ("// AXI Handshakes" . #<marker at 10365 in axi_demux.sv>)
  ("// AXI Handshakes" . #<marker at 18953 in axi_demux.sv>)
  ("// default assignments" . #<marker at 24322 in axi_demux.sv>)
  ("unique case ({push_en[i], inject_en[i], pop_en[i]})" . #<marker at 30693 in axi_demux.sv>))
 ("*Assigns*"
  ("slv_resp_o.aw_ready" . #<marker at 10172 in axi_demux.sv>)
  ("slv_aw_valid" . #<marker at 10243 in axi_demux.sv>)
  ("lookup_aw_select" . #<marker at 13749 in axi_demux.sv>)
  ("aw_select_occupied" . #<marker at 13796 in axi_demux.sv>)
  ("aw_id_cnt_full" . #<marker at 13836 in axi_demux.sv>)
  ("w_select" . #<marker at 15929 in axi_demux.sv>)
  ("w_select_valid" . #<marker at 15997 in axi_demux.sv>)
  ("slv_resp_o.ar_ready" . #<marker at 18768 in axi_demux.sv>)
  ("slv_ar_valid" . #<marker at 18839 in axi_demux.sv>)
  ("lookup_ar_select" . #<marker at 21357 in axi_demux.sv>)
  ("ar_select_occupied" . #<marker at 21404 in axi_demux.sv>)
  ("ar_id_cnt_full" . #<marker at 21444 in axi_demux.sv>)
  ("ar_ready" . #<marker at 24003 in axi_demux.sv>)
  ("aw_ready" . #<marker at 24072 in axi_demux.sv>)
  ("mst_b_chans" . #<marker at 25571 in axi_demux.sv>)
  ("mst_b_valids" . #<marker at 25626 in axi_demux.sv>)
  ("mst_r_chans" . #<marker at 25687 in axi_demux.sv>)
  ("mst_r_valids" . #<marker at 25742 in axi_demux.sv>)
  ("lookup_mst_select_o" . #<marker at 30067 in axi_demux.sv>)
  ("lookup_mst_select_occupied_o" . #<marker at 30138 in axi_demux.sv>)
  ("push_en" . #<marker at 30303 in axi_demux.sv>)
  ("inject_en" . #<marker at 30366 in axi_demux.sv>)
  ("pop_en" . #<marker at 30429 in axi_demux.sv>)
  ("full_o" . #<marker at 30492 in axi_demux.sv>)
  ("occupied" . #<marker at 32226 in axi_demux.sv>)
  ("cnt_full" . #<marker at 32263 in axi_demux.sv>))
 ("*Defines*"
  ("TARGET_VSIM" . #<marker at 1013 in axi_demux.sv>))
 ("*Localparams*"
  ("unsigned" . #<marker at 3473 in axi_demux.sv>)
  ("unsigned" . #<marker at 29683 in axi_demux.sv>))
 ("*Top*"
  ("axi_demux" . #<marker at 1869 in axi_demux.sv>)
  ("axi_demux_id_counters" . #<marker at 28710 in axi_demux.sv>)
  ("axi_demux_intf" . #<marker at 32905 in axi_demux.sv>)))
