// Hierarchy generated by `verilog-ext'

// * ucontroller
// ** cpu
// ** alu
// ** dma
// *** dma_tx
// *** dma_rx
// *** dma_arbiter
// ** uart
// *** uart_tx
// *** uart_rx
// *** sreg
// *** fifo_wrapper
// **** fifo_generator_0
// ***** fifo_generator_0_fifo_generator_v13_2_3
// ****** GND
// ****** VCC
// ****** fifo_generator_0_fifo_generator_v13_2_3_synth
// ******* rf
// ** ram_arbiter
// ** ram
// *** gp_ram
// *** regs_ram
// **** bin2bcd


// * Buffer local variables
// Local Variables:
// eval: (verilog-ext-hierarchy-outshine-nav-mode)
// End:
