#s(hash-table test equal data
	      (("foo" :file "../files/common/misc.sv" :line 2)
	       (:desc "module foo" :col 7)
	       ("bar_pkg" :file "../files/common/misc.sv" :line 3)
	       (:desc "import bar_pkg::*;" :col 7)
	       ("baz_pkg" :file "../files/common/misc.sv" :line 4)
	       (:desc "  import baz_pkg::*;" :col 9)
	       ("clk" :file "../files/common/misc.sv" :line 6)
	       (:desc "  input wire clk," :col 13)
	       ("rst" :file "../files/common/misc.sv" :line 7)
	       (:desc "  input wire rst" :col 13)))
