#s(hash-table test equal data
	      (("test" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 1)
	       (:desc "module test;" :col 7)
	       ("a" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 2)
	       (:desc "  wire a, b, c, d;" :col 7)
	       ("b" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 2)
	       (:desc "  wire a, b, c, d;" :col 10)
	       ("c" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 2)
	       (:desc "  wire a, b, c, d;" :col 13)
	       ("d" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 2)
	       (:desc "  wire a, b, c, d;" :col 16)
	       ("z" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 3)
	       (:desc "  reg z;" :col 6)
	       ("a" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 5)
	       (:desc "    if (a)" :col 8)
	       ("z" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 6)
	       (:desc "      z = a;" :col 6)
	       ("a" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 6)
	       (:desc "      z = a;" :col 10)
	       ("b" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 7)
	       (:desc "    else if (b)" :col 13)
	       ("z" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 8)
	       (:desc "      z = b;" :col 6)
	       ("b" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 8)
	       (:desc "      z = b;" :col 10)
	       ("c" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 10)
	       (:desc "      if (c)" :col 10)
	       ("z" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 11)
	       (:desc "        z = c;" :col 8)
	       ("c" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 11)
	       (:desc "        z = c;" :col 12)
	       ("z" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 13)
	       (:desc "        z = d;" :col 8)
	       ("d" :file "../files/github/tree_sitter_systemverilog_49.sv" :line 13)
	       (:desc "        z = d;" :col 12)))
