#s(hash-table test equal data
	      (("ucontroller" :file "../files/common/ucontroller.sv" :line 21)
	       (:desc "module ucontroller # (" :col 7)
	       ("FREQ_CLK" :file "../files/common/ucontroller.sv" :line 22)
	       (:desc "    parameter logic [31:0] FREQ_CLK = 100000000," :col 27)
	       ("TX_SPEED" :file "../files/common/ucontroller.sv" :line 23)
	       (:desc "    parameter logic [31:0] TX_SPEED = 115200" :col 27)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 25)
	       (:desc "    input logic         Clk," :col 24)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 26)
	       (:desc "    input logic         Rst_n," :col 24)
	       ("RXD" :file "../files/common/ucontroller.sv" :line 28)
	       (:desc "    input logic         RXD," :col 24)
	       ("TXD" :file "../files/common/ucontroller.sv" :line 29)
	       (:desc "    output logic        TXD," :col 24)
	       ("ROM_Data" :file "../files/common/ucontroller.sv" :line 31)
	       (:desc "    input logic [11:0]  ROM_Data," :col 24)
	       ("ROM_Addr" :file "../files/common/ucontroller.sv" :line 32)
	       (:desc "    output logic [11:0] ROM_Addr," :col 24)
	       ("Temp" :file "../files/common/ucontroller.sv" :line 34)
	       (:desc "    output logic [7:0]  Temp," :col 24)
	       ("Switches" :file "../files/common/ucontroller.sv" :line 35)
	       (:desc "    output logic [7:0]  Switches" :col 24)
	       ("DMA_Oen" :file "../files/common/ucontroller.sv" :line 40)
	       (:desc "    logic       DMA_Oen;" :col 16)
	       ("DMA_Wen" :file "../files/common/ucontroller.sv" :line 41)
	       (:desc "    logic       DMA_Wen;" :col 16)
	       ("DMA_Cs" :file "../files/common/ucontroller.sv" :line 42)
	       (:desc "    logic       DMA_Cs;" :col 16)
	       ("CPU_Oen" :file "../files/common/ucontroller.sv" :line 43)
	       (:desc "    logic       CPU_Oen;" :col 16)
	       ("CPU_Wen" :file "../files/common/ucontroller.sv" :line 44)
	       (:desc "    logic       CPU_Wen;" :col 16)
	       ("CPU_Cs" :file "../files/common/ucontroller.sv" :line 45)
	       (:desc "    logic       CPU_Cs;" :col 16)
	       ("CPU_Address" :file "../files/common/ucontroller.sv" :line 46)
	       (:desc "    logic [7:0] CPU_Address;" :col 16)
	       ("DMA_Address" :file "../files/common/ucontroller.sv" :line 47)
	       (:desc "    logic [7:0] DMA_Address;" :col 16)
	       ("DMA_DataOut" :file "../files/common/ucontroller.sv" :line 48)
	       (:desc "    logic [7:0] DMA_DataOut;" :col 16)
	       ("CPU_DataOut" :file "../files/common/ucontroller.sv" :line 49)
	       (:desc "    logic [7:0] CPU_DataOut;" :col 16)
	       ("Dma_Idle" :file "../files/common/ucontroller.sv" :line 50)
	       (:desc "    logic       Dma_Idle;" :col 16)
	       ("TX_Data" :file "../files/common/ucontroller.sv" :line 52)
	       (:desc "    logic [7:0] TX_Data;" :col 16)
	       ("TX_Ready" :file "../files/common/ucontroller.sv" :line 53)
	       (:desc "    logic       TX_Ready;" :col 16)
	       ("TX_Valid" :file "../files/common/ucontroller.sv" :line 54)
	       (:desc "    logic       TX_Valid;" :col 16)
	       ("Data_Read" :file "../files/common/ucontroller.sv" :line 55)
	       (:desc "    logic       Data_Read;" :col 16)
	       ("RX_Data" :file "../files/common/ucontroller.sv" :line 56)
	       (:desc "    logic [7:0] RX_Data;" :col 16)
	       ("RX_Empty" :file "../files/common/ucontroller.sv" :line 57)
	       (:desc "    logic       RX_Empty;" :col 16)
	       ("RX_Full" :file "../files/common/ucontroller.sv" :line 58)
	       (:desc "    logic       RX_Full;" :col 16)
	       ("RAM_DataOut" :file "../files/common/ucontroller.sv" :line 60)
	       (:desc "    logic [7:0] RAM_DataOut;" :col 16)
	       ("RAM_DataIn" :file "../files/common/ucontroller.sv" :line 61)
	       (:desc "    logic [7:0] RAM_DataIn;" :col 16)
	       ("ALU_DataIn" :file "../files/common/ucontroller.sv" :line 63)
	       (:desc "    logic [7:0] ALU_DataIn;" :col 16)
	       ("ALU_DataOut" :file "../files/common/ucontroller.sv" :line 64)
	       (:desc "    logic [7:0] ALU_DataOut;" :col 16)
	       ("alu_op" :file "../files/common/ucontroller.sv" :line 65)
	       (:desc "    alu_op      ALU_op;" :col 4)
	       ("ALU_op" :file "../files/common/ucontroller.sv" :line 65)
	       (:desc "    alu_op      ALU_op;" :col 16)
	       ("FlagE" :file "../files/common/ucontroller.sv" :line 66)
	       (:desc "    logic       FlagE;" :col 16)
	       ("FlagN" :file "../files/common/ucontroller.sv" :line 67)
	       (:desc "    logic       FlagN;" :col 16)
	       ("FlagC" :file "../files/common/ucontroller.sv" :line 68)
	       (:desc "    logic       FlagC;" :col 16)
	       ("FlagZ" :file "../files/common/ucontroller.sv" :line 69)
	       (:desc "    logic       FlagZ;" :col 16)
	       ("RAM_Address" :file "../files/common/ucontroller.sv" :line 71)
	       (:desc "    logic [7:0] RAM_Address;" :col 16)
	       ("RAM_Wen" :file "../files/common/ucontroller.sv" :line 72)
	       (:desc "    logic       RAM_Wen;" :col 16)
	       ("RAM_Oen" :file "../files/common/ucontroller.sv" :line 73)
	       (:desc "    logic       RAM_Oen;" :col 16)
	       ("RAM_Cs" :file "../files/common/ucontroller.sv" :line 74)
	       (:desc "    logic       RAM_Cs;" :col 16)
	       ("Bus_grant" :file "../files/common/ucontroller.sv" :line 76)
	       (:desc "    logic       Bus_grant;" :col 16)
	       ("Bus_req" :file "../files/common/ucontroller.sv" :line 77)
	       (:desc "    logic       Bus_req;" :col 16)
	       ("Dma_Tx_Ready" :file "../files/common/ucontroller.sv" :line 78)
	       (:desc "    logic       Dma_Tx_Ready;" :col 16)
	       ("Dma_Tx_Start" :file "../files/common/ucontroller.sv" :line 79)
	       (:desc "    logic       Dma_Tx_Start;" :col 16)
	       ("cpu" :file "../files/common/ucontroller.sv" :line 83)
	       (:desc "    cpu I_CPU (" :col 4)
	       ("I_CPU" :file "../files/common/ucontroller.sv" :line 83)
	       (:desc "    cpu I_CPU (" :col 8)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 84)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 85)
	       (:desc "        .Rst_n," :col 9)
	       ("ROM_Data" :file "../files/common/ucontroller.sv" :line 87)
	       (:desc "        .ROM_Data," :col 9)
	       ("ROM_Addr" :file "../files/common/ucontroller.sv" :line 88)
	       (:desc "        .ROM_Addr," :col 9)
	       ("RAM_Addr" :file "../files/common/ucontroller.sv" :line 90)
	       (:desc "        .RAM_Addr     (CPU_Address)," :col 9)
	       ("CPU_Address" :file "../files/common/ucontroller.sv" :line 90)
	       (:desc "        .RAM_Addr     (CPU_Address)," :col 23)
	       ("DataOut" :file "../files/common/ucontroller.sv" :line 91)
	       (:desc "        .DataOut      (CPU_DataOut)," :col 9)
	       ("CPU_DataOut" :file "../files/common/ucontroller.sv" :line 91)
	       (:desc "        .DataOut      (CPU_DataOut)," :col 23)
	       ("DataIn" :file "../files/common/ucontroller.sv" :line 92)
	       (:desc "        .DataIn       (RAM_DataOut)," :col 9)
	       ("RAM_DataOut" :file "../files/common/ucontroller.sv" :line 92)
	       (:desc "        .DataIn       (RAM_DataOut)," :col 23)
	       ("RAM_Cs" :file "../files/common/ucontroller.sv" :line 93)
	       (:desc "        .RAM_Cs       (CPU_Cs)," :col 9)
	       ("CPU_Cs" :file "../files/common/ucontroller.sv" :line 93)
	       (:desc "        .RAM_Cs       (CPU_Cs)," :col 23)
	       ("RAM_Wen" :file "../files/common/ucontroller.sv" :line 94)
	       (:desc "        .RAM_Wen      (CPU_Wen)," :col 9)
	       ("CPU_Wen" :file "../files/common/ucontroller.sv" :line 94)
	       (:desc "        .RAM_Wen      (CPU_Wen)," :col 23)
	       ("RAM_Oen" :file "../files/common/ucontroller.sv" :line 95)
	       (:desc "        .RAM_Oen      (CPU_Oen)," :col 9)
	       ("CPU_Oen" :file "../files/common/ucontroller.sv" :line 95)
	       (:desc "        .RAM_Oen      (CPU_Oen)," :col 23)
	       ("DMA_Req" :file "../files/common/ucontroller.sv" :line 97)
	       (:desc "        .DMA_Req      (Bus_req)," :col 9)
	       ("Bus_req" :file "../files/common/ucontroller.sv" :line 97)
	       (:desc "        .DMA_Req      (Bus_req)," :col 23)
	       ("DMA_Ack" :file "../files/common/ucontroller.sv" :line 98)
	       (:desc "        .DMA_Ack      (Bus_grant)," :col 9)
	       ("Bus_grant" :file "../files/common/ucontroller.sv" :line 98)
	       (:desc "        .DMA_Ack      (Bus_grant)," :col 23)
	       ("DMA_Ready" :file "../files/common/ucontroller.sv" :line 99)
	       (:desc "        .DMA_Ready    (Dma_Tx_Ready)," :col 9)
	       ("Dma_Tx_Ready" :file "../files/common/ucontroller.sv" :line 99)
	       (:desc "        .DMA_Ready    (Dma_Tx_Ready)," :col 23)
	       ("DMA_Tx_Start" :file "../files/common/ucontroller.sv" :line 100)
	       (:desc "        .DMA_Tx_Start (Dma_Tx_Start)," :col 9)
	       ("Dma_Tx_Start" :file "../files/common/ucontroller.sv" :line 100)
	       (:desc "        .DMA_Tx_Start (Dma_Tx_Start)," :col 23)
	       ("ALU_op" :file "../files/common/ucontroller.sv" :line 102)
	       (:desc "        .ALU_op," :col 9)
	       ("ALU_DataOut" :file "../files/common/ucontroller.sv" :line 103)
	       (:desc "        .ALU_DataOut," :col 9)
	       ("ALU_DataIn" :file "../files/common/ucontroller.sv" :line 104)
	       (:desc "        .ALU_DataIn," :col 9)
	       ("FlagZ" :file "../files/common/ucontroller.sv" :line 105)
	       (:desc "        .FlagZ," :col 9)
	       ("FlagC" :file "../files/common/ucontroller.sv" :line 106)
	       (:desc "        .FlagC," :col 9)
	       ("FlagN" :file "../files/common/ucontroller.sv" :line 107)
	       (:desc "        .FlagN," :col 9)
	       ("FlagE" :file "../files/common/ucontroller.sv" :line 108)
	       (:desc "        .FlagE" :col 9)
	       ("alu" :file "../files/common/ucontroller.sv" :line 112)
	       (:desc "    alu I_ALU (" :col 4)
	       ("I_ALU" :file "../files/common/ucontroller.sv" :line 112)
	       (:desc "    alu I_ALU (" :col 8)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 113)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 114)
	       (:desc "        .Rst_n," :col 9)
	       ("InData" :file "../files/common/ucontroller.sv" :line 115)
	       (:desc "        .InData  (ALU_DataIn)," :col 9)
	       ("ALU_DataIn" :file "../files/common/ucontroller.sv" :line 115)
	       (:desc "        .InData  (ALU_DataIn)," :col 18)
	       ("OutData" :file "../files/common/ucontroller.sv" :line 116)
	       (:desc "        .OutData (ALU_DataOut)," :col 9)
	       ("ALU_DataOut" :file "../files/common/ucontroller.sv" :line 116)
	       (:desc "        .OutData (ALU_DataOut)," :col 18)
	       ("ALU_op" :file "../files/common/ucontroller.sv" :line 117)
	       (:desc "        .ALU_op," :col 9)
	       ("FlagZ" :file "../files/common/ucontroller.sv" :line 118)
	       (:desc "        .FlagZ," :col 9)
	       ("FlagC" :file "../files/common/ucontroller.sv" :line 119)
	       (:desc "        .FlagC," :col 9)
	       ("FlagN" :file "../files/common/ucontroller.sv" :line 120)
	       (:desc "        .FlagN," :col 9)
	       ("FlagE" :file "../files/common/ucontroller.sv" :line 121)
	       (:desc "        .FlagE" :col 9)
	       ("dma" :file "../files/common/ucontroller.sv" :line 125)
	       (:desc "    dma I_DMA (" :col 4)
	       ("I_DMA" :file "../files/common/ucontroller.sv" :line 125)
	       (:desc "    dma I_DMA (" :col 8)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 126)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 127)
	       (:desc "        .Rst_n," :col 9)
	       ("Bus_grant" :file "../files/common/ucontroller.sv" :line 129)
	       (:desc "        .Bus_grant," :col 9)
	       ("Bus_req" :file "../files/common/ucontroller.sv" :line 130)
	       (:desc "        .Bus_req," :col 9)
	       ("Dma_Tx_Start" :file "../files/common/ucontroller.sv" :line 131)
	       (:desc "        .Dma_Tx_Start," :col 9)
	       ("Dma_Tx_Ready" :file "../files/common/ucontroller.sv" :line 132)
	       (:desc "        .Dma_Tx_Ready," :col 9)
	       ("Dma_Idle" :file "../files/common/ucontroller.sv" :line 133)
	       (:desc "        .Dma_Idle," :col 9)
	       ("RX_Data" :file "../files/common/ucontroller.sv" :line 135)
	       (:desc "        .RX_Data," :col 9)
	       ("RX_Empty" :file "../files/common/ucontroller.sv" :line 136)
	       (:desc "        .RX_Empty," :col 9)
	       ("RX_Full" :file "../files/common/ucontroller.sv" :line 137)
	       (:desc "        .RX_Full," :col 9)
	       ("Data_Read" :file "../files/common/ucontroller.sv" :line 138)
	       (:desc "        .Data_Read," :col 9)
	       ("TX_Ready" :file "../files/common/ucontroller.sv" :line 139)
	       (:desc "        .TX_Ready," :col 9)
	       ("TX_Data" :file "../files/common/ucontroller.sv" :line 140)
	       (:desc "        .TX_Data," :col 9)
	       ("TX_Valid" :file "../files/common/ucontroller.sv" :line 141)
	       (:desc "        .TX_Valid," :col 9)
	       ("Address" :file "../files/common/ucontroller.sv" :line 143)
	       (:desc "        .Address (DMA_Address)," :col 9)
	       ("DMA_Address" :file "../files/common/ucontroller.sv" :line 143)
	       (:desc "        .Address (DMA_Address)," :col 18)
	       ("DataOut" :file "../files/common/ucontroller.sv" :line 144)
	       (:desc "        .DataOut (DMA_DataOut)," :col 9)
	       ("DMA_DataOut" :file "../files/common/ucontroller.sv" :line 144)
	       (:desc "        .DataOut (DMA_DataOut)," :col 18)
	       ("DataIn" :file "../files/common/ucontroller.sv" :line 145)
	       (:desc "        .DataIn  (RAM_DataOut)," :col 9)
	       ("RAM_DataOut" :file "../files/common/ucontroller.sv" :line 145)
	       (:desc "        .DataIn  (RAM_DataOut)," :col 18)
	       ("Cs" :file "../files/common/ucontroller.sv" :line 146)
	       (:desc "        .Cs      (DMA_Cs)," :col 9)
	       ("DMA_Cs" :file "../files/common/ucontroller.sv" :line 146)
	       (:desc "        .Cs      (DMA_Cs)," :col 18)
	       ("Wen" :file "../files/common/ucontroller.sv" :line 147)
	       (:desc "        .Wen     (DMA_Wen)," :col 9)
	       ("DMA_Wen" :file "../files/common/ucontroller.sv" :line 147)
	       (:desc "        .Wen     (DMA_Wen)," :col 18)
	       ("Oen" :file "../files/common/ucontroller.sv" :line 148)
	       (:desc "        .Oen     (DMA_Oen)" :col 9)
	       ("DMA_Oen" :file "../files/common/ucontroller.sv" :line 148)
	       (:desc "        .Oen     (DMA_Oen)" :col 18)
	       ("uart" :file "../files/common/ucontroller.sv" :line 152)
	       (:desc "    uart # (" :col 4)
	       ("FREQ_CLK" :file "../files/common/ucontroller.sv" :line 153)
	       (:desc "        .FREQ_CLK (FREQ_CLK)," :col 19)
	       ("TX_SPEED" :file "../files/common/ucontroller.sv" :line 154)
	       (:desc "        .TX_SPEED (TX_SPEED)" :col 19)
	       ("I_UART" :file "../files/common/ucontroller.sv" :line 155)
	       (:desc "        ) I_UART (" :col 10)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 156)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 157)
	       (:desc "        .Rst_n," :col 9)
	       ("TX_Valid" :file "../files/common/ucontroller.sv" :line 159)
	       (:desc "        .TX_Valid," :col 9)
	       ("TX_DataIn" :file "../files/common/ucontroller.sv" :line 160)
	       (:desc "        .TX_DataIn (TX_Data)," :col 9)
	       ("TX_Data" :file "../files/common/ucontroller.sv" :line 160)
	       (:desc "        .TX_DataIn (TX_Data)," :col 20)
	       ("TX_Ready" :file "../files/common/ucontroller.sv" :line 161)
	       (:desc "        .TX_Ready," :col 9)
	       ("TXD" :file "../files/common/ucontroller.sv" :line 162)
	       (:desc "        .TXD," :col 9)
	       ("Data_Read" :file "../files/common/ucontroller.sv" :line 164)
	       (:desc "        .Data_Read," :col 9)
	       ("Data_Out" :file "../files/common/ucontroller.sv" :line 165)
	       (:desc "        .Data_Out  (RX_Data)," :col 9)
	       ("RX_Data" :file "../files/common/ucontroller.sv" :line 165)
	       (:desc "        .Data_Out  (RX_Data)," :col 20)
	       ("RXD" :file "../files/common/ucontroller.sv" :line 166)
	       (:desc "        .RXD," :col 9)
	       ("Full" :file "../files/common/ucontroller.sv" :line 167)
	       (:desc "        .Full      (RX_Full)," :col 9)
	       ("RX_Full" :file "../files/common/ucontroller.sv" :line 167)
	       (:desc "        .Full      (RX_Full)," :col 20)
	       ("Empty" :file "../files/common/ucontroller.sv" :line 168)
	       (:desc "        .Empty     (RX_Empty)" :col 9)
	       ("RX_Empty" :file "../files/common/ucontroller.sv" :line 168)
	       (:desc "        .Empty     (RX_Empty)" :col 20)
	       ("ram_arbiter" :file "../files/common/ucontroller.sv" :line 172)
	       (:desc "    ram_arbiter I_RAM_ARBITER (" :col 4)
	       ("I_RAM_ARBITER" :file "../files/common/ucontroller.sv" :line 172)
	       (:desc "    ram_arbiter I_RAM_ARBITER (" :col 16)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 173)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 174)
	       (:desc "        .Rst_n," :col 9)
	       ("DMA_Bus_req" :file "../files/common/ucontroller.sv" :line 175)
	       (:desc "        .DMA_Bus_req   (Bus_req)," :col 9)
	       ("Bus_req" :file "../files/common/ucontroller.sv" :line 175)
	       (:desc "        .DMA_Bus_req   (Bus_req)," :col 24)
	       ("DMA_Bus_grant" :file "../files/common/ucontroller.sv" :line 176)
	       (:desc "        .DMA_Bus_grant (Bus_grant)," :col 9)
	       ("Bus_grant" :file "../files/common/ucontroller.sv" :line 176)
	       (:desc "        .DMA_Bus_grant (Bus_grant)," :col 24)
	       ("DMA_Idle" :file "../files/common/ucontroller.sv" :line 177)
	       (:desc "        .DMA_Idle      (Dma_Idle)," :col 9)
	       ("Dma_Idle" :file "../files/common/ucontroller.sv" :line 177)
	       (:desc "        .DMA_Idle      (Dma_Idle)," :col 24)
	       ("CPU_DataOut" :file "../files/common/ucontroller.sv" :line 178)
	       (:desc "        .CPU_DataOut," :col 9)
	       ("DMA_DataOut" :file "../files/common/ucontroller.sv" :line 179)
	       (:desc "        .DMA_DataOut," :col 9)
	       ("RAM_DataIn" :file "../files/common/ucontroller.sv" :line 180)
	       (:desc "        .RAM_DataIn," :col 9)
	       ("CPU_Address" :file "../files/common/ucontroller.sv" :line 181)
	       (:desc "        .CPU_Address," :col 9)
	       ("DMA_Address" :file "../files/common/ucontroller.sv" :line 182)
	       (:desc "        .DMA_Address," :col 9)
	       ("RAM_Address" :file "../files/common/ucontroller.sv" :line 183)
	       (:desc "        .RAM_Address," :col 9)
	       ("CPU_Cs" :file "../files/common/ucontroller.sv" :line 184)
	       (:desc "        .CPU_Cs," :col 9)
	       ("DMA_Cs" :file "../files/common/ucontroller.sv" :line 185)
	       (:desc "        .DMA_Cs," :col 9)
	       ("RAM_Cs" :file "../files/common/ucontroller.sv" :line 186)
	       (:desc "        .RAM_Cs," :col 9)
	       ("CPU_Oen" :file "../files/common/ucontroller.sv" :line 187)
	       (:desc "        .CPU_Oen," :col 9)
	       ("DMA_Oen" :file "../files/common/ucontroller.sv" :line 188)
	       (:desc "        .DMA_Oen," :col 9)
	       ("RAM_Oen" :file "../files/common/ucontroller.sv" :line 189)
	       (:desc "        .RAM_Oen," :col 9)
	       ("CPU_Wen" :file "../files/common/ucontroller.sv" :line 190)
	       (:desc "        .CPU_Wen," :col 9)
	       ("DMA_Wen" :file "../files/common/ucontroller.sv" :line 191)
	       (:desc "        .DMA_Wen," :col 9)
	       ("RAM_Wen" :file "../files/common/ucontroller.sv" :line 192)
	       (:desc "        .RAM_Wen" :col 9)
	       ("ram" :file "../files/common/ucontroller.sv" :line 197)
	       (:desc "    ram I_RAM (" :col 4)
	       ("I_RAM" :file "../files/common/ucontroller.sv" :line 197)
	       (:desc "    ram I_RAM (" :col 8)
	       ("Clk" :file "../files/common/ucontroller.sv" :line 198)
	       (:desc "        .Clk," :col 9)
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 199)
	       (:desc "        .Rst_n," :col 9)
	       ("Cs" :file "../files/common/ucontroller.sv" :line 200)
	       (:desc "        .Cs      (RAM_Cs)," :col 9)
	       ("RAM_Cs" :file "../files/common/ucontroller.sv" :line 200)
	       (:desc "        .Cs      (RAM_Cs)," :col 18)
	       ("Wen" :file "../files/common/ucontroller.sv" :line 201)
	       (:desc "        .Wen     (RAM_Wen)," :col 9)
	       ("RAM_Wen" :file "../files/common/ucontroller.sv" :line 201)
	       (:desc "        .Wen     (RAM_Wen)," :col 18)
	       ("Oen" :file "../files/common/ucontroller.sv" :line 202)
	       (:desc "        .Oen     (RAM_Oen)," :col 9)
	       ("RAM_Oen" :file "../files/common/ucontroller.sv" :line 202)
	       (:desc "        .Oen     (RAM_Oen)," :col 18)
	       ("Address" :file "../files/common/ucontroller.sv" :line 203)
	       (:desc "        .Address (RAM_Address)," :col 9)
	       ("RAM_Address" :file "../files/common/ucontroller.sv" :line 203)
	       (:desc "        .Address (RAM_Address)," :col 18)
	       ("DataIn" :file "../files/common/ucontroller.sv" :line 204)
	       (:desc "        .DataIn  (RAM_DataIn)," :col 9)
	       ("RAM_DataIn" :file "../files/common/ucontroller.sv" :line 204)
	       (:desc "        .DataIn  (RAM_DataIn)," :col 18)
	       ("DataOut" :file "../files/common/ucontroller.sv" :line 205)
	       (:desc "        .DataOut (RAM_DataOut)," :col 9)
	       ("RAM_DataOut" :file "../files/common/ucontroller.sv" :line 205)
	       (:desc "        .DataOut (RAM_DataOut)," :col 18)
	       ("Switches" :file "../files/common/ucontroller.sv" :line 206)
	       (:desc "        .Switches," :col 9)
	       ("Temp" :file "../files/common/ucontroller.sv" :line 207)
	       (:desc "        .Temp" :col 9)
	       ("ucontroller" :file "../files/common/ucontroller.sv" :line 213)
	       (:desc "endmodule: ucontroller" :col 11)))
