#s(hash-table test equal data
	      (("FREQ_CLK" :file "../files/common/ucontroller.sv" :line 22)
	       (:type "parameter_declaration" :desc "    parameter logic [31:0] FREQ_CLK = 100000000," :col 4 :parent "ucontroller")
	       ("TX_SPEED" :file "../files/common/ucontroller.sv" :line 23)
	       (:type "parameter_declaration" :desc "    parameter logic [31:0] TX_SPEED = 115200" :col 4 :parent "ucontroller")
	       ("Clk" :file "../files/common/ucontroller.sv" :line 25)
	       (:type "input logic" :desc "    input logic         Clk," :col 4 :parent "ucontroller")
	       ("Rst_n" :file "../files/common/ucontroller.sv" :line 26)
	       (:type "input logic" :desc "    input logic         Rst_n," :col 4 :parent "ucontroller")
	       ("RXD" :file "../files/common/ucontroller.sv" :line 28)
	       (:type "input logic" :desc "    input logic         RXD," :col 4 :parent "ucontroller")
	       ("TXD" :file "../files/common/ucontroller.sv" :line 29)
	       (:type "output logic" :desc "    output logic        TXD," :col 4 :parent "ucontroller")
	       ("ROM_Data" :file "../files/common/ucontroller.sv" :line 31)
	       (:type "input logic [11:0]" :desc "    input logic [11:0]  ROM_Data," :col 4 :parent "ucontroller")
	       ("ROM_Addr" :file "../files/common/ucontroller.sv" :line 32)
	       (:type "output logic [11:0]" :desc "    output logic [11:0] ROM_Addr," :col 4 :parent "ucontroller")
	       ("Temp" :file "../files/common/ucontroller.sv" :line 34)
	       (:type "output logic [7:0]" :desc "    output logic [7:0]  Temp," :col 4 :parent "ucontroller")
	       ("Switches" :file "../files/common/ucontroller.sv" :line 35)
	       (:type "output logic [7:0]" :desc "    output logic [7:0]  Switches" :col 4 :parent "ucontroller")
	       ("DMA_Oen" :file "../files/common/ucontroller.sv" :line 40)
	       (:type "logic" :desc "    logic       DMA_Oen;" :col 16 :parent "ucontroller")
	       ("DMA_Wen" :file "../files/common/ucontroller.sv" :line 41)
	       (:type "logic" :desc "    logic       DMA_Wen;" :col 16 :parent "ucontroller")
	       ("DMA_Cs" :file "../files/common/ucontroller.sv" :line 42)
	       (:type "logic" :desc "    logic       DMA_Cs;" :col 16 :parent "ucontroller")
	       ("CPU_Oen" :file "../files/common/ucontroller.sv" :line 43)
	       (:type "logic" :desc "    logic       CPU_Oen;" :col 16 :parent "ucontroller")
	       ("CPU_Wen" :file "../files/common/ucontroller.sv" :line 44)
	       (:type "logic" :desc "    logic       CPU_Wen;" :col 16 :parent "ucontroller")
	       ("CPU_Cs" :file "../files/common/ucontroller.sv" :line 45)
	       (:type "logic" :desc "    logic       CPU_Cs;" :col 16 :parent "ucontroller")
	       ("CPU_Address" :file "../files/common/ucontroller.sv" :line 46)
	       (:type "logic [7:0]" :desc "    logic [7:0] CPU_Address;" :col 16 :parent "ucontroller")
	       ("DMA_Address" :file "../files/common/ucontroller.sv" :line 47)
	       (:type "logic [7:0]" :desc "    logic [7:0] DMA_Address;" :col 16 :parent "ucontroller")
	       ("DMA_DataOut" :file "../files/common/ucontroller.sv" :line 48)
	       (:type "logic [7:0]" :desc "    logic [7:0] DMA_DataOut;" :col 16 :parent "ucontroller")
	       ("CPU_DataOut" :file "../files/common/ucontroller.sv" :line 49)
	       (:type "logic [7:0]" :desc "    logic [7:0] CPU_DataOut;" :col 16 :parent "ucontroller")
	       ("Dma_Idle" :file "../files/common/ucontroller.sv" :line 50)
	       (:type "logic" :desc "    logic       Dma_Idle;" :col 16 :parent "ucontroller")
	       ("TX_Data" :file "../files/common/ucontroller.sv" :line 52)
	       (:type "logic [7:0]" :desc "    logic [7:0] TX_Data;" :col 16 :parent "ucontroller")
	       ("TX_Ready" :file "../files/common/ucontroller.sv" :line 53)
	       (:type "logic" :desc "    logic       TX_Ready;" :col 16 :parent "ucontroller")
	       ("TX_Valid" :file "../files/common/ucontroller.sv" :line 54)
	       (:type "logic" :desc "    logic       TX_Valid;" :col 16 :parent "ucontroller")
	       ("Data_Read" :file "../files/common/ucontroller.sv" :line 55)
	       (:type "logic" :desc "    logic       Data_Read;" :col 16 :parent "ucontroller")
	       ("RX_Data" :file "../files/common/ucontroller.sv" :line 56)
	       (:type "logic [7:0]" :desc "    logic [7:0] RX_Data;" :col 16 :parent "ucontroller")
	       ("RX_Empty" :file "../files/common/ucontroller.sv" :line 57)
	       (:type "logic" :desc "    logic       RX_Empty;" :col 16 :parent "ucontroller")
	       ("RX_Full" :file "../files/common/ucontroller.sv" :line 58)
	       (:type "logic" :desc "    logic       RX_Full;" :col 16 :parent "ucontroller")
	       ("RAM_DataOut" :file "../files/common/ucontroller.sv" :line 60)
	       (:type "logic [7:0]" :desc "    logic [7:0] RAM_DataOut;" :col 16 :parent "ucontroller")
	       ("RAM_DataIn" :file "../files/common/ucontroller.sv" :line 61)
	       (:type "logic [7:0]" :desc "    logic [7:0] RAM_DataIn;" :col 16 :parent "ucontroller")
	       ("ALU_DataIn" :file "../files/common/ucontroller.sv" :line 63)
	       (:type "logic [7:0]" :desc "    logic [7:0] ALU_DataIn;" :col 16 :parent "ucontroller")
	       ("ALU_DataOut" :file "../files/common/ucontroller.sv" :line 64)
	       (:type "logic [7:0]" :desc "    logic [7:0] ALU_DataOut;" :col 16 :parent "ucontroller")
	       ("ALU_op" :file "../files/common/ucontroller.sv" :line 65)
	       (:type "alu_op" :desc "    alu_op      ALU_op;" :col 16 :parent "ucontroller")
	       ("FlagE" :file "../files/common/ucontroller.sv" :line 66)
	       (:type "logic" :desc "    logic       FlagE;" :col 16 :parent "ucontroller")
	       ("FlagN" :file "../files/common/ucontroller.sv" :line 67)
	       (:type "logic" :desc "    logic       FlagN;" :col 16 :parent "ucontroller")
	       ("FlagC" :file "../files/common/ucontroller.sv" :line 68)
	       (:type "logic" :desc "    logic       FlagC;" :col 16 :parent "ucontroller")
	       ("FlagZ" :file "../files/common/ucontroller.sv" :line 69)
	       (:type "logic" :desc "    logic       FlagZ;" :col 16 :parent "ucontroller")
	       ("RAM_Address" :file "../files/common/ucontroller.sv" :line 71)
	       (:type "logic [7:0]" :desc "    logic [7:0] RAM_Address;" :col 16 :parent "ucontroller")
	       ("RAM_Wen" :file "../files/common/ucontroller.sv" :line 72)
	       (:type "logic" :desc "    logic       RAM_Wen;" :col 16 :parent "ucontroller")
	       ("RAM_Oen" :file "../files/common/ucontroller.sv" :line 73)
	       (:type "logic" :desc "    logic       RAM_Oen;" :col 16 :parent "ucontroller")
	       ("RAM_Cs" :file "../files/common/ucontroller.sv" :line 74)
	       (:type "logic" :desc "    logic       RAM_Cs;" :col 16 :parent "ucontroller")
	       ("Bus_grant" :file "../files/common/ucontroller.sv" :line 76)
	       (:type "logic" :desc "    logic       Bus_grant;" :col 16 :parent "ucontroller")
	       ("Bus_req" :file "../files/common/ucontroller.sv" :line 77)
	       (:type "logic" :desc "    logic       Bus_req;" :col 16 :parent "ucontroller")
	       ("Dma_Tx_Ready" :file "../files/common/ucontroller.sv" :line 78)
	       (:type "logic" :desc "    logic       Dma_Tx_Ready;" :col 16 :parent "ucontroller")
	       ("Dma_Tx_Start" :file "../files/common/ucontroller.sv" :line 79)
	       (:type "logic" :desc "    logic       Dma_Tx_Start;" :col 16 :parent "ucontroller")
	       ("ucontroller" :file "../files/common/ucontroller.sv" :line 21)
	       (:type "module_declaration" :desc "module ucontroller # (" :col 0 :parent nil)))
