#s(hash-table test equal data
	      (("clk" :file "../files/github/verilog_ext_37.sv" :line 11)
	       (:type "input wire" :desc "   input wire clk;" :col 14 :parent "reset_generator")
	       ("rst_async" :file "../files/github/verilog_ext_37.sv" :line 12)
	       (:type "input" :desc "   input      rst_async; // asynchronous reset" :col 14 :parent "reset_generator")
	       ("rst_n" :file "../files/github/verilog_ext_37.sv" :line 13)
	       (:type "output" :desc "   output     rst_n;    // synchronous reset" :col 14 :parent "reset_generator")
	       ("unused" :file "../files/github/verilog_ext_37.sv" :line 15)
	       (:type "input" :desc "   input      unused, unused2; // Added to test tags for list_of_port_identifiers" :col 14 :parent "reset_generator")
	       ("unused2" :file "../files/github/verilog_ext_37.sv" :line 15)
	       (:type "input" :desc "   input      unused, unused2; // Added to test tags for list_of_port_identifiers" :col 14 :parent "reset_generator")
	       ("rst_async_m" :file "../files/github/verilog_ext_37.sv" :line 23)
	       (:type "reg" :desc "   reg        rst_async_m; // can be metastable" :col 14 :parent "reset_generator")
	       ("rst_async_r" :file "../files/github/verilog_ext_37.sv" :line 24)
	       (:type "reg" :desc "   reg        rst_async_r; // can be metastable" :col 14 :parent "reset_generator")
	       ("reset_generator" :file "../files/github/verilog_ext_37.sv" :line 4)
	       (:type "module_declaration" :desc "module reset_generator (/*AUTOARG*/" :col 0 :parent nil)))
