#s(hash-table test equal data
	      (("foo" :file "../files/github/verilog_ext_29.sv" :line 1)
	       (:desc "module foo;" :col 7)
	       ("foo_module" :file "../files/github/verilog_ext_29.sv" :line 3)
	       (:desc "foo_module #(" :col 0)
	       ("G_SOME_CONSTANT" :file "../files/github/verilog_ext_29.sv" :line 4)
	       (:desc ".G_SOME_CONSTANT (   5)," :col 1)
	       ("G_SOME_OTHER_CONSTANT" :file "../files/github/verilog_ext_29.sv" :line 5)
	       (:desc ".G_SOME_OTHER_CONSTANT (   5)," :col 1)
	       ("G_EVEN_SOME_OTHER_CONSTANT" :file "../files/github/verilog_ext_29.sv" :line 6)
	       (:desc ".G_EVEN_SOME_OTHER_CONSTANT     (  )" :col 1)
	       ("my_foo" :file "../files/github/verilog_ext_29.sv" :line 7)
	       (:desc ") my_foo (" :col 2)
	       ("clk" :file "../files/github/verilog_ext_29.sv" :line 8)
	       (:desc ".clk    (my_clk                           ), // asdf" :col 1)
	       ("my_clk" :file "../files/github/verilog_ext_29.sv" :line 8)
	       (:desc ".clk    (my_clk                           ), // asdf" :col 9)
	       ("reset" :file "../files/github/verilog_ext_29.sv" :line 9)
	       (:desc ".reset ( my_reset)," :col 1)
	       ("my_reset" :file "../files/github/verilog_ext_29.sv" :line 9)
	       (:desc ".reset ( my_reset)," :col 9)
	       ("port_a" :file "../files/github/verilog_ext_29.sv" :line 12)
	       (:desc ".port_a (my_a                             ),// asdf 2" :col 1)
	       ("my_a" :file "../files/github/verilog_ext_29.sv" :line 12)
	       (:desc ".port_a (my_a                             ),// asdf 2" :col 9)
	       ("port_b" :file "../files/github/verilog_ext_29.sv" :line 13)
	       (:desc ".port_b( my_b                             ),            // asdf3" :col 1)
	       ("my_b" :file "../files/github/verilog_ext_29.sv" :line 13)
	       (:desc ".port_b( my_b                             ),            // asdf3" :col 9)
	       ("port_c" :file "../files/github/verilog_ext_29.sv" :line 16)
	       (:desc ".port_c   ( my_c                             )," :col 1)
	       ("my_c" :file "../files/github/verilog_ext_29.sv" :line 16)
	       (:desc ".port_c   ( my_c                             )," :col 12)
	       ("port_d" :file "../files/github/verilog_ext_29.sv" :line 17)
	       (:desc ".port_d ( my_d                             )," :col 1)
	       ("my_d" :file "../files/github/verilog_ext_29.sv" :line 17)
	       (:desc ".port_d ( my_d                             )," :col 10)
	       ("port_e" :file "../files/github/verilog_ext_29.sv" :line 20)
	       (:desc ".port_e," :col 1)
	       ("port_f" :file "../files/github/verilog_ext_29.sv" :line 21)
	       (:desc ".port_f" :col 1)))
