#s(hash-table test equal data
	      (("reset_generator" :file "../files/github/verilog_ext_37.sv" :line 4)
	       (:desc "module reset_generator (/*AUTOARG*/" :col 7)
	       ("rst_n" :file "../files/github/verilog_ext_37.sv" :line 6)
	       (:desc "                        rst_n," :col 24)
	       ("clk" :file "../files/github/verilog_ext_37.sv" :line 8)
	       (:desc "                        clk, rst_async" :col 24)
	       ("rst_async" :file "../files/github/verilog_ext_37.sv" :line 8)
	       (:desc "                        clk, rst_async" :col 29)
	       ("clk" :file "../files/github/verilog_ext_37.sv" :line 11)
	       (:desc "   input wire clk;" :col 14)
	       ("rst_async" :file "../files/github/verilog_ext_37.sv" :line 12)
	       (:desc "   input      rst_async; // asynchronous reset" :col 14)
	       ("rst_n" :file "../files/github/verilog_ext_37.sv" :line 13)
	       (:desc "   output     rst_n;    // synchronous reset" :col 14)
	       ("unused" :file "../files/github/verilog_ext_37.sv" :line 15)
	       (:desc "   input      unused, unused2; // Added to test tags for list_of_port_identifiers" :col 14)
	       ("unused2" :file "../files/github/verilog_ext_37.sv" :line 15)
	       (:desc "   input      unused, unused2; // Added to test tags for list_of_port_identifiers" :col 22)
	       ("rst_async_m" :file "../files/github/verilog_ext_37.sv" :line 23)
	       (:desc "   reg        rst_async_m; // can be metastable" :col 14)
	       ("rst_async_r" :file "../files/github/verilog_ext_37.sv" :line 24)
	       (:desc "   reg        rst_async_r; // can be metastable" :col 14)
	       ("clk" :file "../files/github/verilog_ext_37.sv" :line 26)
	       (:desc "   always @(negedge clk or negedge rst_async) begin" :col 20)
	       ("rst_async" :file "../files/github/verilog_ext_37.sv" :line 26)
	       (:desc "   always @(negedge clk or negedge rst_async) begin" :col 35)
	       ("rst_async" :file "../files/github/verilog_ext_37.sv" :line 27)
	       (:desc "      if(rst_async == 1'b0) begin" :col 9)
	       ("rst_async_m" :file "../files/github/verilog_ext_37.sv" :line 30)
	       (:desc "         rst_async_m <= 1'h0;" :col 9)
	       ("rst_async_r" :file "../files/github/verilog_ext_37.sv" :line 31)
	       (:desc "         rst_async_r <= 1'h0;" :col 9)
	       ("rst_async_m" :file "../files/github/verilog_ext_37.sv" :line 35)
	       (:desc "         rst_async_m <= 1'b1; // Can be metastable" :col 9)
	       ("rst_async_r" :file "../files/github/verilog_ext_37.sv" :line 36)
	       (:desc "         rst_async_r <= rst_async_m;" :col 9)
	       ("rst_async_m" :file "../files/github/verilog_ext_37.sv" :line 36)
	       (:desc "         rst_async_r <= rst_async_m;" :col 24)
	       ("rst_n" :file "../files/github/verilog_ext_37.sv" :line 41)
	       (:desc "   assign rst_n = rst_async_r;" :col 10)
	       ("rst_async_r" :file "../files/github/verilog_ext_37.sv" :line 41)
	       (:desc "   assign rst_n = rst_async_r;" :col 18)
	       ("reset_generator" :file "../files/github/verilog_ext_37.sv" :line 46)
	       (:desc "endmodule : reset_generator" :col 12)))
