#s(hash-table test equal data
	      (("pkg_member" :file "../files/github/verilog_ext_3.sv" :line 5)
	       (:type "int" :desc "        int pkg_member;" :col 12 :parent "pkg_cls")
	       ("pkg_var" :file "../files/github/verilog_ext_3.sv" :line 7)
	       (:type "logic / [5][$]" :desc "        logic pkg_var [5][$];" :col 14 :parent "pkg_cls")
	       ("name" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:type "string" :desc "        function new(string name=\"asdf\", uvm_component parent);" :col 21 :parent "new")
	       ("parent" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:type "uvm_component" :desc "        function new(string name=\"asdf\", uvm_component parent);" :col 41 :parent "new")
	       ("new" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:type "class_constructor_declaration" :desc "        function new(string name=\"asdf\", uvm_component parent);" :col 8 :parent "pkg_cls")
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 4)
	       (:type "class_declaration" :desc "    class pkg_cls;" :col 4 :parent "foo_pkg")
	       ("foo_pkg" :file "../files/github/verilog_ext_3.sv" :line 1)
	       (:type "package_declaration" :desc "package foo_pkg;" :col 0 :parent nil)
	       ("cls_inst" :file "../files/github/verilog_ext_3.sv" :line 20)
	       (:type "pkg_cls" :desc "    pkg_cls cls_inst;" :col 12 :parent "foo")
	       ("var2" :file "../files/github/verilog_ext_3.sv" :line 22)
	       (:type "logic / [5][$]" :desc "    logic       var2 [5][$];" :col 16 :parent "foo")
	       ("var3" :file "../files/github/verilog_ext_3.sv" :line 23)
	       (:type "logic / [5]" :desc "    logic       var3 [5];" :col 16 :parent "foo")
	       ("var4" :file "../files/github/verilog_ext_3.sv" :line 24)
	       (:type "wire [7:0] / [5]" :desc "    wire [7:0]  var4 [5];" :col 16 :parent "foo")
	       ("var5" :file "../files/github/verilog_ext_3.sv" :line 25)
	       (:type "wire [7:0] / [$]" :desc "    wire [7:0]  var5 [$] = '{0, 1};" :col 16 :parent "foo")
	       ("var6" :file "../files/github/verilog_ext_3.sv" :line 26)
	       (:type "wire [7:0] / []" :desc "    wire [7:0]  var6 [];" :col 16 :parent "foo")
	       ("var7" :file "../files/github/verilog_ext_3.sv" :line 27)
	       (:type "wire [7:0] / [7]" :desc "    wire [7:0]  var7 [7];" :col 16 :parent "foo")
	       ("var8" :file "../files/github/verilog_ext_3.sv" :line 28)
	       (:type "logic [7:0] / [int]" :desc "    logic [7:0] var8 [int];" :col 16 :parent "foo")
	       ("A" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:type "enum_name_declaration" :desc "    typedef enum logic [2:0] {A, B} type_t;" :col 30 :parent "type_t")
	       ("B" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:type "enum_name_declaration" :desc "    typedef enum logic [2:0] {A, B} type_t;" :col 33 :parent "type_t")
	       ("type_t" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:type "enum logic [2:0] {A, B}" :desc "    typedef enum logic [2:0] {A, B} type_t;" :col 4 :parent "foo")
	       ("my_type" :file "../files/github/verilog_ext_3.sv" :line 31)
	       (:type "type_t" :desc "    type_t my_type;" :col 11 :parent "foo")
	       ("A" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:type "enum_name_declaration" :desc "    enum logic [2:0] {A, B} var_e;" :col 22 :parent "var_e")
	       ("B" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:type "enum_name_declaration" :desc "    enum logic [2:0] {A, B} var_e;" :col 25 :parent "var_e")
	       ("var_e" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:type "enum logic [2:0] {A, B}" :desc "    enum logic [2:0] {A, B} var_e;" :col 28 :parent "foo")
	       ("s" :file "../files/github/verilog_ext_3.sv" :line 34)
	       (:type "string" :desc "    string s;" :col 11 :parent "foo")
	       ("a" :file "../files/github/verilog_ext_3.sv" :line 60)
	       (:type "struct_union_member" :desc "        int a;" :col 8 :parent "my_struct_t")
	       ("b" :file "../files/github/verilog_ext_3.sv" :line 61)
	       (:type "struct_union_member" :desc "        logic b;" :col 8 :parent "my_struct_t")
	       ("c" :file "../files/github/verilog_ext_3.sv" :line 62)
	       (:type "struct_union_member" :desc "        type_t c;" :col 8 :parent "my_struct_t")
	       ("my_struct_t" :file "../files/github/verilog_ext_3.sv" :line 59)
	       (:type "struct {\n        int a;\n        logic b;\n        type_t c;\n    }" :desc "    typedef struct {" :col 4 :parent "foo")
	       ("my_struct" :file "../files/github/verilog_ext_3.sv" :line 65)
	       (:type "my_struct_t" :desc "    my_struct_t my_struct;" :col 16 :parent "foo")
	       ("a" :file "../files/github/verilog_ext_3.sv" :line 68)
	       (:type "struct_union_member" :desc "        int a;" :col 8 :parent "my_struct_2")
	       ("b" :file "../files/github/verilog_ext_3.sv" :line 69)
	       (:type "struct_union_member" :desc "        logic b;" :col 8 :parent "my_struct_2")
	       ("c" :file "../files/github/verilog_ext_3.sv" :line 70)
	       (:type "struct_union_member" :desc "        type_t c;" :col 8 :parent "my_struct_2")
	       ("my_struct_2" :file "../files/github/verilog_ext_3.sv" :line 67)
	       (:type "data_type_or_implicit" :desc "    struct {" :col 4 :parent "foo")
	       ("my_struct_2" :file "../files/github/verilog_ext_3.sv" :line 71)
	       (:type "struct {\n        int a;\n        logic b;\n        type_t c;\n    }" :desc "    } my_struct_2;" :col 6 :parent "foo")
	       ("foo" :file "../files/github/verilog_ext_3.sv" :line 18)
	       (:type "module_declaration" :desc "module foo;" :col 0 :parent nil)
	       ("foo_fun_arg" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:type "input logic [$clog2(NUM_BITS)-1:0] / [NUM_BITS]" :desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 31 :parent "foo_function")
	       ("foo_function" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:type "function_declaration" :desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 4 :parent "foo_tf_args")
	       ("foo_task_arg" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:type "input logic [$clog2(NUM_BITS)-1:0] / [NUM_BITS]" :desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 27 :parent "foo_task")
	       ("foo_task" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:type "function_declaration" :desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 4 :parent "foo_tf_args")
	       ("foo_tf_args" :file "../files/github/verilog_ext_3.sv" :line 79)
	       (:type "module_declaration" :desc "module foo_tf_args;" :col 0 :parent nil)))
