#s(hash-table test equal data
	      (("foo_pkg" :file "../files/github/verilog_ext_3.sv" :line 1)
	       (:desc "package foo_pkg;" :col 8)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 4)
	       (:desc "    class pkg_cls;" :col 10)
	       ("pkg_member" :file "../files/github/verilog_ext_3.sv" :line 5)
	       (:desc "        int pkg_member;" :col 12)
	       ("pkg_var" :file "../files/github/verilog_ext_3.sv" :line 7)
	       (:desc "        logic pkg_var [5][$];" :col 14)
	       ("new" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:desc "        function new(string name=\"asdf\", uvm_component parent);" :col 17)
	       ("name" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:desc "        function new(string name=\"asdf\", uvm_component parent);" :col 28)
	       ("uvm_component" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:desc "        function new(string name=\"asdf\", uvm_component parent);" :col 41)
	       ("parent" :file "../files/github/verilog_ext_3.sv" :line 9)
	       (:desc "        function new(string name=\"asdf\", uvm_component parent);" :col 55)
	       ("new" :file "../files/github/verilog_ext_3.sv" :line 10)
	       (:desc "            super.new(name, parent);" :col 18)
	       ("name" :file "../files/github/verilog_ext_3.sv" :line 10)
	       (:desc "            super.new(name, parent);" :col 22)
	       ("parent" :file "../files/github/verilog_ext_3.sv" :line 10)
	       (:desc "            super.new(name, parent);" :col 28)
	       ("new" :file "../files/github/verilog_ext_3.sv" :line 11)
	       (:desc "        endfunction : new" :col 22)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 13)
	       (:desc "    endclass: pkg_cls" :col 14)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 15)
	       (:desc "endpackage : pkg_cls" :col 13)
	       ("foo" :file "../files/github/verilog_ext_3.sv" :line 18)
	       (:desc "module foo;" :col 7)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 20)
	       (:desc "    pkg_cls cls_inst;" :col 4)
	       ("cls_inst" :file "../files/github/verilog_ext_3.sv" :line 20)
	       (:desc "    pkg_cls cls_inst;" :col 12)
	       ("var2" :file "../files/github/verilog_ext_3.sv" :line 22)
	       (:desc "    logic       var2 [5][$];" :col 16)
	       ("var3" :file "../files/github/verilog_ext_3.sv" :line 23)
	       (:desc "    logic       var3 [5];" :col 16)
	       ("var4" :file "../files/github/verilog_ext_3.sv" :line 24)
	       (:desc "    wire [7:0]  var4 [5];" :col 16)
	       ("var5" :file "../files/github/verilog_ext_3.sv" :line 25)
	       (:desc "    wire [7:0]  var5 [$] = '{0, 1};" :col 16)
	       ("var6" :file "../files/github/verilog_ext_3.sv" :line 26)
	       (:desc "    wire [7:0]  var6 [];" :col 16)
	       ("" :file "../files/github/verilog_ext_3.sv" :line 26)
	       (:desc "    wire [7:0]  var6 [];" :col 22)
	       ("var7" :file "../files/github/verilog_ext_3.sv" :line 27)
	       (:desc "    wire [7:0]  var7 [7];" :col 16)
	       ("var8" :file "../files/github/verilog_ext_3.sv" :line 28)
	       (:desc "    logic [7:0] var8 [int];" :col 16)
	       ("A" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:desc "    typedef enum logic [2:0] {A, B} type_t;" :col 30)
	       ("B" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:desc "    typedef enum logic [2:0] {A, B} type_t;" :col 33)
	       ("type_t" :file "../files/github/verilog_ext_3.sv" :line 30)
	       (:desc "    typedef enum logic [2:0] {A, B} type_t;" :col 36)
	       ("type_t" :file "../files/github/verilog_ext_3.sv" :line 31)
	       (:desc "    type_t my_type;" :col 4)
	       ("my_type" :file "../files/github/verilog_ext_3.sv" :line 31)
	       (:desc "    type_t my_type;" :col 11)
	       ("A" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:desc "    enum logic [2:0] {A, B} var_e;" :col 22)
	       ("B" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:desc "    enum logic [2:0] {A, B} var_e;" :col 25)
	       ("var_e" :file "../files/github/verilog_ext_3.sv" :line 32)
	       (:desc "    enum logic [2:0] {A, B} var_e;" :col 28)
	       ("s" :file "../files/github/verilog_ext_3.sv" :line 34)
	       (:desc "    string s;" :col 11)
	       ("cls_inst" :file "../files/github/verilog_ext_3.sv" :line 37)
	       (:desc "    cls_inst." :col 4)
	       ("var2" :file "../files/github/verilog_ext_3.sv" :line 38)
	       (:desc "    var2." :col 4)
	       ("var3" :file "../files/github/verilog_ext_3.sv" :line 39)
	       (:desc "    var3." :col 4)
	       ("var4" :file "../files/github/verilog_ext_3.sv" :line 40)
	       (:desc "    var4." :col 4)
	       ("var5" :file "../files/github/verilog_ext_3.sv" :line 41)
	       (:desc "    var5." :col 4)
	       ("var6" :file "../files/github/verilog_ext_3.sv" :line 42)
	       (:desc "    var6." :col 4)
	       ("var7" :file "../files/github/verilog_ext_3.sv" :line 43)
	       (:desc "    var7." :col 4)
	       ("var8" :file "../files/github/verilog_ext_3.sv" :line 44)
	       (:desc "    var8." :col 4)
	       ("my_type" :file "../files/github/verilog_ext_3.sv" :line 45)
	       (:desc "    my_type." :col 4)
	       ("var_e" :file "../files/github/verilog_ext_3.sv" :line 46)
	       (:desc "    var_e." :col 4)
	       ("foo_pkg" :file "../files/github/verilog_ext_3.sv" :line 50)
	       (:desc "        foo_pkg::" :col 8)
	       ("foo_pkg" :file "../files/github/verilog_ext_3.sv" :line 51)
	       (:desc "        foo_pkg::pkg_cls::" :col 8)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 51)
	       (:desc "        foo_pkg::pkg_cls::" :col 17)
	       ("foo_pkg" :file "../files/github/verilog_ext_3.sv" :line 52)
	       (:desc "        foo_pkg::pkg_cls::pkg_var." :col 8)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 52)
	       (:desc "        foo_pkg::pkg_cls::pkg_var." :col 17)
	       ("pkg_var" :file "../files/github/verilog_ext_3.sv" :line 52)
	       (:desc "        foo_pkg::pkg_cls::pkg_var." :col 26)
	       ("pkg_cls" :file "../files/github/verilog_ext_3.sv" :line 53)
	       (:desc "        pkg_cls::" :col 8)
	       ("a" :file "../files/github/verilog_ext_3.sv" :line 60)
	       (:desc "        int a;" :col 12)
	       ("b" :file "../files/github/verilog_ext_3.sv" :line 61)
	       (:desc "        logic b;" :col 14)
	       ("type_t" :file "../files/github/verilog_ext_3.sv" :line 62)
	       (:desc "        type_t c;" :col 8)
	       ("c" :file "../files/github/verilog_ext_3.sv" :line 62)
	       (:desc "        type_t c;" :col 15)
	       ("my_struct_t" :file "../files/github/verilog_ext_3.sv" :line 63)
	       (:desc "    } my_struct_t;" :col 6)
	       ("my_struct_t" :file "../files/github/verilog_ext_3.sv" :line 65)
	       (:desc "    my_struct_t my_struct;" :col 4)
	       ("my_struct" :file "../files/github/verilog_ext_3.sv" :line 65)
	       (:desc "    my_struct_t my_struct;" :col 16)
	       ("a" :file "../files/github/verilog_ext_3.sv" :line 68)
	       (:desc "        int a;" :col 12)
	       ("b" :file "../files/github/verilog_ext_3.sv" :line 69)
	       (:desc "        logic b;" :col 14)
	       ("type_t" :file "../files/github/verilog_ext_3.sv" :line 70)
	       (:desc "        type_t c;" :col 8)
	       ("c" :file "../files/github/verilog_ext_3.sv" :line 70)
	       (:desc "        type_t c;" :col 15)
	       ("my_struct_2" :file "../files/github/verilog_ext_3.sv" :line 71)
	       (:desc "    } my_struct_2;" :col 6)
	       ("my_struct" :file "../files/github/verilog_ext_3.sv" :line 73)
	       (:desc "    my_struct." :col 4)
	       ("my_struct_2" :file "../files/github/verilog_ext_3.sv" :line 74)
	       (:desc "    my_struct_2." :col 4)
	       ("foo" :file "../files/github/verilog_ext_3.sv" :line 76)
	       (:desc "endmodule : foo" :col 12)
	       ("foo_tf_args" :file "../files/github/verilog_ext_3.sv" :line 79)
	       (:desc "module foo_tf_args;" :col 7)
	       ("foo_function" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 18)
	       ("$clog2" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 44)
	       ("NUM_BITS" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 79)
	       ("foo_fun_arg" :file "../files/github/verilog_ext_3.sv" :line 81)
	       (:desc "    function void foo_function(input logic [$clog2(NUM_BITS)-1:0] foo_fun_arg [NUM_BITS]);" :col 66)
	       ("foo_function" :file "../files/github/verilog_ext_3.sv" :line 83)
	       (:desc "    endfunction : foo_function" :col 18)
	       ("foo_task" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 18)
	       ("$clog2" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 40)
	       ("NUM_BITS" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 76)
	       ("foo_task_arg" :file "../files/github/verilog_ext_3.sv" :line 85)
	       (:desc "    function void foo_task(input logic [$clog2(NUM_BITS)-1:0] foo_task_arg [NUM_BITS]);" :col 62)
	       ("foo_task" :file "../files/github/verilog_ext_3.sv" :line 87)
	       (:desc "    endfunction : foo_task" :col 18)
	       ("foo_fun_arg" :file "../files/github/verilog_ext_3.sv" :line 90)
	       (:desc "    foo_fun_arg." :col 4)
	       ("foo_task_arg" :file "../files/github/verilog_ext_3.sv" :line 91)
	       (:desc "    foo_task_arg." :col 4)
	       ("foo_tf_args" :file "../files/github/verilog_ext_3.sv" :line 93)
	       (:desc "endmodule : foo_tf_args" :col 12)))
